apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
- ../istio

patchesStrategicMerge:
- config-map.yaml
#- deployment.yaml

configMapGenerator:
- name: dex
  behavior: merge
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: ldap_host
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.ldap_host
- name: ldap_bind_dn
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.ldap_bind_dn
- name: ldap_bind_pw
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.ldap_bind_pw
- name: ldap_user_base_dn
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.ldap_user_base_dn
- name: ldap_group_base_dn
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.ldap_group_base_dn
- name: client_id
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.client_id
- name: oidc_redirect_uris
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.oidc_redirect_uris
- name: application_secret
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.application_secret
- name: issuer
  objref:
    kind: ConfigMap
    name: dex
    apiVersion: v1
  fieldref:
    fieldpath: data.issuer
configurations:
- params.yaml
